---
version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
      - '29093:29093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092, EXTERNAL_SAME_HOST://:29092, EXTERNAL_DIFFERENT_HOST://:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092, EXTERNAL_SAME_HOST://localhost:29092, EXTERNAL_DIFFERENT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL_SAME_HOST:PLAINTEXT, EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ksqldb-server:
    container_name: ksqldb-server
    image: confluentinc/ksqldb-server:latest
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - '8088:8088'
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'

  ksqldb-cli:
    container_name: ksqldb-cli
    image: confluentinc/ksqldb-cli:latest
    restart: unless-stopped
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    volumes:
      - ./ksql/ksql-init.sql:/tmp/ksql-init.sql
    tty: true

  kafka-producer:
    container_name: kafka-producer
    image: ml/producer
    build: ./
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      NUM_MESSAGES: 100
