-- docker exec -it ksqldb-cli ksql http://ksqldb-server:8088
SET
  'auto.offset.reset' = 'latest';

CREATE STREAM STREAM_EVENT_ALL (
  id VARCHAR,
  type VARCHAR,
  payload STRUCT < user_id VARCHAR,
  timestamp INT >
) WITH(
  KAFKA_TOPIC = 'dev_events',
  VALUE_FORMAT = 'JSON'
);

CREATE STREAM STREAM_EVENT_ALL_KEYED AS
SELECT
  *
FROM
  STREAM_EVENT_ALL PARTITION BY id;

CREATE STREAM STREAM_EVENT_ACCOUNT_CREATED AS
SELECT
  *
FROM
  STREAM_EVENT_ALL
WHERE
  type = 'AccountCreated';

CREATE STREAM STREAM_EVENT_ACCOUNT_DELETED AS
SELECT
  *
FROM
  STREAM_EVENT_ALL
WHERE
  type = 'AccountDeleted';

CREATE TABLE TABLE_EVENT_ALL (id VARCHAR PRIMARY KEY, type VARCHAR) WITH(
  KAFKA_TOPIC = 'STREAM_EVENT_ALL_KEYED',
  VALUE_FORMAT = 'JSON'
);

CREATE TABLE TABLE_EVENT_ACCOUNT_DELETED AS
SELECT
  *
FROM
  TABLE_EVENT_ALL
WHERE
  type = 'AccountDeleted';